global:
  environment: dev

db:
  auth:
    password: "dev-password-123"
    postgresPassword: "dev-admin-123"
  image:
    tag: "15.6.0-debian-11-r16"

backend:
  replicaCount: 1
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

frontend:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

ingress:
  host: dev.parcial1.ejemplo.com
