# ─────────────────────────────────────────
#  VALUES PARA ENTORNO PROD
# ─────────────────────────────────────────
global:
  environment: prod

db:
  image:
    tag: "15.6.0-debian-11-r16"
  auth:
    # En prod: pasar con --set en pipeline CI/CD, NUNCA hardcodear
    password: ""
    postgresPassword: ""
  primary:
    persistence:
      size: 1Gi
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

backend:
  image:
    repository: suryaputraku/spring-boot-crud
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

frontend:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

ingress:
  host: parcial1.ejemplo.com
