# ─────────────────────────────────────────
#  VALUES PARA ENTORNO DEV
# ─────────────────────────────────────────
global:
  environment: dev

db:
  auth:
    password: "dev-password-123"
    postgresPassword: "dev-admin-123"
  primary:
    persistence:
      size: 2Gi
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi

backend:
  replicaCount: 1
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

frontend:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

ingress:
  host: dev.pedido.ejemplo.com
