# ─────────────────────────────────────────
#  GLOBAL
# ─────────────────────────────────────────
global:
  environment: base

# ─────────────────────────────────────────
#  BASE DE DATOS (Bitnami PostgreSQL)
# ─────────────────────────────────────────
db:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: "15.7.0"
    pullPolicy: IfNotPresent
  auth:
    username: pedidouser
    password: ""
    database: pedidodb
    postgresPassword: ""
  primary:
    persistence:
      enabled: true
      size: 1Gi
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

# ─────────────────────────────────────────
#  BACKEND (Spring Boot)
# ─────────────────────────────────────────
backend:
  image:
    repository: docker.io/pankajsinghal/spring-boot-postgres
    tag: latest

# ─────────────────────────────────────────
#  FRONTEND (React/Nginx)
# ─────────────────────────────────────────
frontend:
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# ─────────────────────────────────────────
#  INGRESS
# ─────────────────────────────────────────
ingress:
  enabled: true
  className: nginx
  host: parcial1.ejemplo.com
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
