apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parcial1-prod
  namespace: argocd
  labels:
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    # ⚠️ Reemplaza con la URL real de tu repositorio GitHub
    repoURL: https://github.com/Juanfelipejaime/Parcial_1-Patrones-arquitectonicos-avanzados-JFJ/new/main/environments.git
    targetRevision: HEAD
    path: charts/parcial1
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: parcial1-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
