apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "parcial1.fullname" . }}-backend-config
  labels:
    app.kubernetes.io/name: {{ include "parcial1.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  SPRING_DATASOURCE_URL: {{ .Values.backend.env.SPRING_DATASOURCE_URL | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.backend.env.SPRING_DATASOURCE_USERNAME | quote }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  SERVER_PORT: "8080"
  ENVIRONMENT: {{ .Values.global.environment | quote }}
