apiVersion: v1
kind: Service
metadata:
  name: {{ include "parcial1.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "parcial1.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "parcial1.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
