apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pedido-app.fullname" . }}-db-secret
  labels:
    app.kubernetes.io/name: {{ include "pedido-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  # Las credenciales se encodean en base64 automáticamente con b64enc
  db-password: {{ .Values.db.auth.password | b64enc | quote }}
  db-username: {{ .Values.db.auth.username | b64enc | quote }}
