apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parcial1-dev
  namespace: argocd
  labels:
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Juanfelipejaime/Parcial_1-Patrones-arquitectonicos-avanzados-JFJ.git
    targetRevision: HEAD
    path: charts/parcial1
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: parcial1-dev

  syncPolicy:
    automated:
      prune: true       # Elimina recursos que ya no están en Git
      selfHeal: true    # Reconcilia si alguien toca el clúster a mano
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
